languaje: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli bower
install:
- npm install
- bower install
script: grunt build:dev
deploy:
  provider: openshift
  user: jaureguifacundo@gmail.com
  password:
    secure: eG9THBqraXFvUSCAShnHzK/ukaG5vmTG8OqiR5omrT7a0x6pbTtgblzR+h7ZQSAcrto2K+UHcQY9f/ME6ITPu0g4lMWtdtR9ClSQTzo2TEphchXs+oDA5kOp1Xae79MvAoa8npahYsxyNOshIftbf4O8I2GAkOWJ0jwlViJq5vx6S/Bm36tWqwQuc23VnR9Qksvck2blQZR4sTczLtr5LCWIz0ganqEiD2BmfBoYBUxBLFx1WOfogT0DaTqdohzp4rHCNjq/fhrWJ7d/29POKazHSN3FWTbHiWDq7ihgwJwRk98+/I0Td7HTmRRV7O60+qksoiC/yjZQeeyTQ/Naqk2YMn1QGE7AgdwXXKHsc2xEe5eXUL3LEJBbPYrPkXuUc5WDHcbM6/ISbwgjp7Hw7IthYxBIQ5ZfqgPT2+sDJLVfLgheT0PIFDElJ7z35DUPZbLdfV3c9SMYhIA1nwleFnXPLvZKb0SZwB523knJ4Tf1C16sC80rIOg53uArhTGFlfn0xtWOP/5XqnWeTGmDbQmc/2Xs+J7BZeRYTIDTg5x33gxxdURIWei2l6uf9pWLV31neY7+FCbP4S+glBS2tNIsNKkUW1aJeKZcjloSzKHJlx2JTlLdmFmWuEj3q2LzhdIF3Zw8kW4ucfQbppCY5friiKVh23UOwBCoXEB63BY=
  app: retrotool
  domain: howtonode
  skip_cleanup: true
